name: Cipheria
description: A Full Stack AI Chatbot built via Flutter and Firebase, harnessing the power of powerful Gemini Pro (LLM) Model.

publish_to: 'firebase'

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: '^4.0.3'
  flutter_dotenv: ^5.0.2
  simple_gradient_text: '^1.3.0'
  firebase_core: 2.31.1
  cloud_firestore: 4.17.4
  firebase_storage: 11.6.9
  flutterfire_cli: ^1.0.0
  cloud_firestore_odm: 1.0.0-dev.84
  flutter_animate: any
  url_launcher: ^6.2.6
  google_generative_ai: ^0.4.0
  dotenv: ^4.2.0
  firebase_auth: ^4.19.6
  random_string_generator: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/